### ISSUE TITLE
Galerie / file: Sortierung in 2.2.0 nicht möglich

### ISSUE THREAD

**Issue by k-webdesign** [MetaModels/attribute_file#104]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.4       |                                  |
| Contao version:                     |   4.9.20       |                                  |
| MetaModels version:                 |   2.2.0       |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |          |                                  |

## Issue description

Die manuelle Bildsortierung funkioniert in der 2.2.0 noch nicht. Musste die DCA-Anpassung (dcasetting, rendersetting) dazu eintragen

## Steps to reproduce

1. In der Eingabemaske im Attribut "file" nachschauen. Keine Sortierung standardmäßig möglich.

## Describe the behaviour of the application

(Tell us what happens)

## Describe the expected behaviour of the application

Sortierung sollte laut Ingolf in der 2.2.0 drin sein

## Screenshots

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment]
Ich habe das bei 6 verschiedenene Instaolltionen geprüft - auch eine (relativ) frische... an den Dateien hat sich seit 2019 nichts geändert.... habe mal @MacKP die Links zu den Repos gesendet... müsst ihr mal nachgucken, ob die "vollstädig" sind und wenn ja ob der Install klemmt...
