### ISSUE TITLE
Files can only downloaded if they are protected

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_file#105]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.4       |                                  |
| Contao version:                     |    4.9.x      |                                  |
| MetaModels version:                 |   2.2       |                                  |
| Installation via composer           | yes |                                  |

## Issue description

Im Frontend will ich das File als Download ausgeben. Ein Link wird generiert in der Art: https://meineseite.de/detailseite.html?file=files/arg/pdf.pdf
Angekreutzt ist im Backend auch 'Link als Download oder Lightbox darstellen'.
Bei Klick auf den Link läd die Seite neu und man hat nur die URL mit den Parametern hinten dran.
Es fehlt das (von Contao inzwischen übliche `&CID=xxx` am Ende der URL. Wenn ich das von Hand hinzufüge, dann geht der Download.
Ich kann im Backend auch 'Protected download' aktiv stellen, damit das erst mal funktioniert. Ist nur unschön, da der hash ja immer wieder neu erstellt wird.

Randbemerkung:
`$this->settings->get('file_showLink'))` ist 'null' und die Abfrage funktioniert deswegen auch nicht.

Viele Grüße

**Comment by zonky2** [comment]
fixed in MM 2.2
