### ISSUE TITLE
Bug with Contao 3.3

### ISSUE THREAD

**Issue by jantheofel** [MetaModels/attribute_file#30]
This attribute with Contao 3.3 has a bug when choosing "Passen Sie den Dateibaum an." This produces an PHP error:

Fatal error: Uncaught exception RuntimeException with message Unsupported getter function for 'activeRecord' in DC_General. thrown in composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/DC_General.php on line 660

**Comment by dmolineus** [comment]
Kann ich in Contao 3.4.5 nicht nachvollziehen. Kennt jemand das Problem aus der 3.4er Version? Falls es ein Cto 3.3 spezifisches Problem ist, empfehle ich dies nicht zu fixen, da der Support für Contao 3.3 ausgelaufen ist.

**Comment by tim-bec** [comment]
confused why i mentioned this ticket to @dmolineus ... we should not support contao 3.3
