### ISSUE TITLE
Ansicht im BE übereinanders vs. CTO nebeneinander

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/attribute_file#33]
Hi,

im CTO core werden bei Mehrfachauswahl die Bilder als Thumbnails im Grid nebeneinander angezeigt, in MM übereinander. Das ist bei Auswahl vieler Bilder etwas unübersichtlich ...

![2014-08-09_13_39_14_-_galerie_-_contao_open_source_cms_3_3](https://cloud.githubusercontent.com/assets/4976687/3865996/d16452f4-1fb9-11e4-9afd-bed83dbb06ec.png)
vs
![2014-08-09_13_39_58_-_artikel_galerie_inhaltselement_id_102_bearbeiten_-_contao_open_source_cms_3_3](https://cloud.githubusercontent.com/assets/4976687/3865999/eb283a7a-1fb9-11e4-8541-da9a277fc94c.png)

**Comment by discordier** [comment]
@zonky2 ist das nicht mit #52 erledigt?

**Comment by zonky2** [comment]
muss ich nochmal testen...

**Comment by zonky2** [comment]
es gibt ein Widget in drei "Geschmacksrichtungen"

![shot298](https://cloud.githubusercontent.com/assets/1045318/20784705/5594f00c-b79c-11e6-9cdf-bf2252ae7276.jpg)

**No 1**

![shot298_1](https://cloud.githubusercontent.com/assets/1045318/20784732/7479ff58-b79c-11e6-9091-f5ac20348f96.jpg)

**No 2**

![shot298_2](https://cloud.githubusercontent.com/assets/1045318/20784739/79be87a4-b79c-11e6-8d7e-da58f8ba1be0.jpg)

**No 3**

![shot298_3](https://cloud.githubusercontent.com/assets/1045318/20784743/8198af2c-b79c-11e6-9b46-7cc6e88b451b.jpg)
