### ISSUE TITLE
Feature Request: upload im BE während der Bearbeitung eines MM Eintrages

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/attribute_file#35]
Hi,
ich würde mal ganz vorsichtig anfragen, ob es möglich wäre das File Attribut konfigurierbar mit upload features zu erweitern? 

Gefunden habe ich z.B. den fineuploader; ich habe versucht, terminal42/contao-fineuploader einfach mal in File.php getFieldDefinition() einzupflegen, leider scheitert es an der Ajax-Verarbeitung über DCG. Und leider kenne ich mich auch nicht in den Strukturen von MM+DCG aus, um das selbst zu machen.

Es ist nicht wichtig, ob das der fineuploader, der Contao-interne uploader oder eine anderer ist. Was wichtig ist, wäre folgendes:
- Auswahl im BE (wie bisher beim file Attribut)
- Upload mehrerer Files im BE direkt im Formular (direkt oder modal) und sofortige Zuordnung zu dem bearbeiteten MM Eintrag (neu)
- Löschen der Files direkt im Formular (wie das X neben den Files bei terminal42/contao-fineuploader) (neu)

Perfekt wäre es, wenn konfigurierbare Optionen für folgendes da wäre:
- Upload in bestehendes Verzeichnis (wie bisher) ODER neues Verzeichnis z.B. aktuelles Datum oder alias/id des MM Eintrages (neu)
- Löschen der zugeordneten files eines MM Eintrages, wenn der MM Eintrag gelöscht wird (neu)

Vorteile: Workflow viel einfacher und offensichtlicher, als über mehrere Popups, Verzeichnis anlegen und Dateiverwaltung zu gehen. Dateileichen entfallen dann auch, wenn die Files mitgelöscht werden (nach Anwendungsfall).

**Comment by cyberlussi** [comment]
Neben terminal42/contao-fineuploader wollte ich den seit 3.3.0 verfügbaren Contao internen Dropzone uploader noch ins Spiel bringen. Das würde die externen Abhängigkeiten reduzieren.

**Comment by discordier** [comment]
Das ist allgemein eine Anbindung der jeweiligen Uploader an den DCG. Wenn diese geschaffen sind, dann kann man es in MM auch nutzbar machen.

**Comment by zonky2** [comment]
Im Auswahlwidget für Dateien ab Contao 4.8 kann man direkt in der Lightbox per D&D ein oder mehrere Bilder in einen Ordner ziehen
