### ISSUE TITLE
Folder selector needs more clicks than Contao to display files

### ISSUE THREAD

**Issue by Teetrinker** [MetaModels/attribute_file#36]
I am not sure, if this is a problem of attribute_file, hope this issue is placed right

##How we know it from Contao
Create a Contao Content Element, type image ("Bild"), choose source (Quelldatei)
click plus before folder -> results in display of images contained in this folder

##How it happens in Metamodels
Have Metamodel with field of type 'folder'
Go to the input screen (Eingabemaske), edit an item
Open folder chooser (Dateiwähler)
Click on plus before folder name, nothing happens. (but it should)
Click on folder name - now the images contained in this folder are shown.

Contao 3.3.3 with nightly build from 2014-09-30

**Comment by discordier** [comment]
Should be fixed I guess. In the end, we are using the Contao standard file picker as base now.

If it is not fixed, please create a new ticket in MetaModels/core, as the picker is contained in there.

**Comment by Teetrinker** [comment]
Thanks, great to see MM tickets getting processed.
