### ISSUE TITLE
Contao 3.3.7, aktuelles Metamodel ->Fehler, wenn "Dateibaum anpassen" aktiv

### ISSUE THREAD

**Issue by Znrl** [MetaModels/attribute_file#39]
Ich habe ein ein  metamodels bei dem ein bild ausgewählt werden soll.
Sobald ich das Häkchen bei "Passen Sie den Dateibaum an" setze kommt ein Fehler/Waring und es wird nichts mehr angezeigt.
Hab mit den Optionen schon rumgespielt und es ändert sich nicht, ich seh auch kein Unterschied zum Dateipicker?
```
Warning: is_dir() expects parameter 1 to be a valid path, string given in system/modules/core/widgets/FileSelector.php on line 193

#0 [internal function]: __error(2, 'is_dir() expect...', '/var/www/virtua...', 193, Array)
#1 system/modules/core/widgets/FileSelector.php(193): is_dir('/var/www/virtua...')
#2 system/modules/core/widgets/FileSelector.php(92): Contao\FileSelector->renderFiletree('/var/www/virtua...', 0)
#3 contao/file.php(112): Contao\FileSelector->generate()
#4 contao/file.php(136): FilePicker->run()
#5 {main}
```
Den Wurzelordner hab ich auch auf alles mögliche geändert.
Ohne angepassten Dateibaum funktioniert es. Wäre nur praktisch direkt auf den passenden Ordner zu zeigen.

**Comment by cboelter** [comment]
Ich habe das gleiche Problem, es liegt meiner Meinung nach an dieser Zeile: https://github.com/MetaModels/attribute_file/commit/f8b72fd6ed5540e614691537495c41ae5fe12ad9#diff-427c155aaa3a5060709eadfc3c0543fcR169

Ich habe die Prüfung einmal auf folgendes geändert ```if (\Validator::isUuid($this->get('file_uploadFolder'))) {```damit tut es wieder bei mir.

**Comment by discordier** [comment]
Ist behoben.
