### ISSUE TITLE
Metadaten der Files werden nicht geladen

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_file#41]
Wenn ich Im Template auf die Metadaten des Bildes zugreifen will sind die Keys im Array zwar aufgeführt, aber nicht befüllt.

Wie komme ich da trotzdem ran?

```php
[0]=>
  array(17) {
    ["file"]=>
    string(42) "files/content/projekte/2.png"
    ["mtime"]=>
    int(1423654621)
    ["alt"]=>
    string(15) "2"
    ["caption"]=>
    string(0) ""
    ["title"]=>
    string(19) "2.png"
    ["metafile"]=>
    array(3) {
      ["title"]=>
      string(0) ""
      ["link"]=>
      string(0) ""
      ["caption"]=>
      string(0) ""
    }
    ["icon"]=>
    string(32) "assets/contao/images/iconTIF.gif"
    ["size"]=>
    int(1560776)
    ["sizetext"]=>
    string(10) "(1.49 MiB)"
    ["url"]=>
    string(57) "de/?file=files%2Fcontent%2Fprojekte%2F2.png"
    ["isGdImage"]=>
    bool(true)
    ["src"]=>
    string(44) "assets/images/6/2-dae86346.png"
    ["lb"]=>
    string(18) "lbmm_projects.13.5"
    ["w"]=>
    int(600)
    ["h"]=>
    int(396)
    ["wh"]=>
    string(24) "width="600" height="396""
    ["class"]=>
    string(16) " first last even"
  }
```

**Comment by dmolineus** [comment]
Ich kann dies nicht reproduzieren in einem einfachen MM. Wie ist denn dein Setting?

* Nutzt du ein mehrsprachiges MM?
* Tritt dies im Backend oder Frontend auf?
* In welcher Sprache ist deine Seite?
* Für welche Sprachen existieren die Bilder-Metadaten?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?
