### ISSUE TITLE
Fehler wenn Wurzel-Verzeichnis angewählt

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_file#42]
Wenn ich ein Wurzelverzeichnis für den Dateipicker auswähle kommt folgende Fehlermeldung:
![bildschirmfoto 2015-03-19 um 11 06 37](https://cloud.githubusercontent.com/assets/1016798/6728218/93a83fac-ce28-11e4-91a6-783f7a38483d.png)

Ohne Wurzelverzeichnis passt alles (bis auf das Wurtzelverzeichnis eben ;-))
![bildschirmfoto 2015-03-19 um 11 09 57](https://cloud.githubusercontent.com/assets/1016798/6728217/93923004-ce28-11e4-96c8-6100d2327fcd.png)

Bei mir ist das beim TranslatedFile passiert und zwar mit der Contao 3.2.19
Ich vermute aber dass es ein allgemeines Problem ist (daher Ticket hier)

**Comment by discordier** [comment]
@stefanheimes as you are working on the file handling currently, could you have a look at this as well?

**Comment by discordier** [comment]
@psren Kannst du das bitte mit der aktuellsten Version nochmal testen? Ich hoffe ich habe dein Problem mit erschlagen.

**Comment by psren** [comment]
Related to #39

**Comment by psren** [comment]
Und ich kann leider nicht testen ob das mit dem Wurzelverzeichnis grade funktioniert, da ich diesen Fehler bekomme: #44

**Comment by discordier** [comment]
Sollte behoben sein, ansonten bitte neues Ticket.
