### ISSUE TITLE
Crop mode "An Rahmen anpassen" ändert die Bilder proportional

### ISSUE THREAD

**Issue by psren** [MetaModels/attribute_file#43]
Die Bilder werden wenn sie Hochkant sind nur proportional skaliert.
Ich glaube das sollte anders sein.

![bildschirmfoto 2015-03-19 um 15 57 48](https://cloud.githubusercontent.com/assets/1016798/6733183/c4235388-ce50-11e4-9840-36fedb522df1.png)

**Comment by discordier** [comment]
Verhaelt sich das anders als im Contao core?

Probier bitte mal aus wie es dort laeuft, wenn du bei einem text element ein eigenes Bild auswaehlst.
Eigentlich verwenden wir hier genau den selben Weg wie dort. 

Wenn beidesmal dasselbe passiert, dann gehoert das nach https://github.com/contao/core.

**Comment by psren** [comment]
Es passiert nicht das selbe.
Wenn ich das beim Attribut einstelle bekomme ich ein proportional skaliertes Bild für Hochkant-Bilder.

Das hier führt aber zu dem richtigen Resultat:
```html
<img src="<?= $this->getImage($image, 510, 380, 'center_center'); ?>" alt="" />
```

**Comment by discordier** [comment]
Bitte nochmal testen ob das inzwischen behoben ist.
@tim-bec Evtl. kannst du auch was dazu sagen?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?
