### ISSUE TITLE
Fatal error: Call to undefined method MetaModels\Helper\ToolboxFile::convertValuesToMeta Models()

### ISSUE THREAD

**Issue by andre5tz** [MetaModels/attribute_file#49]
Hallo,

nach meinem heutigen Update von MM über Composer bekomme ich beim Aufruf eines MM die folgende Fehlermeldung:

>Fatal error: Call to undefined method MetaModels\Helper\ToolboxFile::convertValuesToMeta Models() in .../composer/vendor/metamodels/attribute_file/src/MetaModels/Attribute/File/File.php on line 104

Contao 3.2.21
contao-community-alliance/dc-general dev-develop (388f7a7c) → 2.0.x-dev
metamodels/core dev-tng (e750d21) → 2.0.x-dev
metamodels/bundle_all 1.0.1

Ausgangssituation:
Wenn ich im Backend ein Metamodel auswähle (link z.B. auf http://www.xxx.de/contao/main.php?do=metamodel_mm_sitzungsdienst&ref=6b0f907a), dann kommt die oben genannte Fehlermeldung. Voraussetzung scheint zu sein, dass in dem Metamodel ein file-attribute vorhanden ist.

Im Frontend kommt die gleiche Fehlermeldung, wenn das file-attribute vorhanden ist. 
Wird in den Rendereinstellungen für das Frontend die Datei abgewählt (Auge-Symbol), dann funktioniert das Frontend wieder ohne Fehlermeldung.

Im Backend hilft mir das Abschalten (Auge-Symbol) nichts.
Cache leeren bring auch keine Veränderung.

Beim Versuch, das ganze nachzustellen habe ich bei einem vorhandenen MetaModel ein Datei-Attribut hinzugefügt. Nach der Auswahl eines Bildes kam dann die folgende Fehlermeldung:

> Datei

> Fatal error: Call to undefined method MetaModels\Helper\ToolboxFile::convertUuidsOrPathsToMetaModels() in /www/htdocs/w00e56c3/contao-core/contao-3-2-lts/composer/vendor/metamodels/attribute_file/src/MetaModels/Attribute/File/File.php on line 212

Ein Klick auf Speichern bringt dann nochmal die Fehlermeldung und es wird keine Datei zu dem Datensatz gespeichert.

Ein neues MM zum Testen aufbauen kann ich leider nicht, da mir #792 (https://github.com/MetaModels/core/issues/792#issuecomment-132509855) in die Quere kommt.

Wenn ich noch irgendwie helfen kann, dann gerne im Rahmen meiner Möglichkeiten. Backendzugang kann z.B. gerne eingerichtet werden.

VG
André

**Comment by discordier** [comment]
Siehe Kommentar im von dir verlinkten ticket. Du hast alte Informationen und Versionen.

**Comment by andre5tz** [comment]
Danke für die Info, mir war nicht bekannt, dass ich das umstellen muss, muss ich wohl verpasst haben. Leider steht das so noch nicht auf now.metamodels.me, wäre vielleicht noch einen Hinweis wert.

LG und DANKE :-)
