### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 139866527699016 bytes) in Unknown on line 0

### ISSUE THREAD

**Issue by gruenerPetz** [MetaModels/attribute_file#50]
Hallo,

wir haben folgendes Problem: Sobald im Backend ein Bild gesendet wird, finden wir im php error log folgende Nachricht:

`PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 139866527699016 bytes) in Unknown on line 0`

Nicht zuverlässig reproduzierbar bekommen wir eine leere Seite nach dem Speichern.

Habt ihr evtl. einen Tipp für uns, was das sein kann?

**Comment by zonky2** [comment]
was bedeutet

>Sobald im Backend ein Bild **gesendet** wird

**Comment by gruenerPetz** [comment]
Wir benutzen das File Attribute und wenn ein Bild gewählt wird kommt der Fehler. Wird kein Bild gewählt wird, ist alles super.

**Comment by zonky2** [comment]
passiert der Fehler auch, wenn das selbe Bild im "normalen Contao" verwendet wird? Wurde das Bild per FTP oder über die Dateiverwaltung hoch geladen?

**Comment by gruenerPetz** [comment]
Ich habe jetzt zwei Varianten getestet:

1. Img 1931 x 1931 px (1.1 MiB) - upload SAMBA
2. Img 600 x 600 (330,6 KiB) - upload Contao Dateiverwaltung

Normales Contao Bild Inhaltselement funktionieren beide ohne Probleme.
MM bei beiden der Fehler.

**Comment by zonky2** [comment]
hmm... aktuelles MM?
bitte prüfen, ob die Bilder wirklich das sind, was die Extension vorgibt

**Comment by gruenerPetz** [comment]
Contao: 3.5.9
metamodels/core: 2.0.0-alpha10
metamodels/attribute_file: 2.0.0-alpha1

was meinst du mit
> bitte prüfen, ob die Bilder wirklich das sind, was die Extension vorgibt

**Comment by zonky2** [comment]
mach mal Contao auf die .12 - da gabs ein paar Bug mit Dateien - glaube ich...

zur Prüfung: nur weil ein Bild "my_picture.**jpg**" heißt, muss das kein JPEG sein...

**Comment by gruenerPetz** [comment]
Bild ist 100%ig ein Bild :) Fehler tritt auch bei anderen Bildern auf.
Contao update auf .12 habe ich gemacht. Selber Verhalten.

**Comment by zonky2** [comment]
o.k. - die GDlib kommt ins straucheln, wenn man z.B. ein PNG als my_picture.jpg hoch läd...

ansonsten habe ich erstmal keine Idee, warum hier "mehre Terabyte" Speicher "gewünscht" werden...

such mal bitte die Apache und PHP-Version raus

**Comment by discordier** [comment]
Any update?

**Comment by zonky2** [comment]
@gruenerPetz bitte Infos zum aktuellen Stand!

**Comment by gruenerPetz** [comment]
Ich habe Apache und PHP inkl. alle Module noch mal neu aufgesetzt und seitdem tritt der Fehler nicht mehr auf. Ich denke es hing mit der GBlib zusammen, da das Problem definitiv beim resizen der Bilder aufgetreten ist. Danke für die Hilfe!

**Comment by stefanmeschke** [comment]
Der Fehler tritt bei uns erneut auf und nicht nur bei Bildern.
Aktuell tritt dies bei jeder hochgeladenen PDF-Datei auf.

Habt ihr eine Idee, was dies sein könnte? Danke!

**Comment by zonky2** [comment]
@stefanmeschke bitte Infos zu Contao + MM + PHP usw. - könnt Ihr debuggen, wann/wo der Fehler auftritt?

**Comment by stefanmeschke** [comment]
@zonky2 
Es handelt sich um das selbe System (selbe Server) wie von @gruenerPetz.

**Comment by gruenerPetz** [comment]
Contao:  3.5.12
metamodels/core: 2.0.0-alpha10
metamodels/attribute_file: dev-master

OS: Ubuntu
PHP: 5.6.20
Apache: 2.4.20 (Ubuntu)

Ich habe die Stelle noch nicht gefunden, wo genau der Fehler auftritt.

**Comment by zonky2** [comment]
in https://github.com/MetaModels/attribute_file/issues/50#issuecomment-217989022 hieß es, es tritt nicht mehr auf - nun doch (wieder)..?

**Comment by stefanmeschke** [comment]
Ja, das stimmt. Dies kann aber auch daran liegen, dass wir in den letzten 2 Wochen eher wenig mit Dateien gemacht haben.
Das Problem tritt auch nicht immer auf, sondern oft, aber manchmal scheint es auch zu gehen.

**Comment by zonky2** [comment]
könnt ihr probieren
* DCG auf beta35
* ggf. MMcore auf alpha11

**Comment by gruenerPetz** [comment]
Wir sind genau so ratlos. Es ist definitiv die Kombination Server - Contao. Btw. es betrifft auch nicht nur die eine Contao Installation sondern alle auf dem Server.

**Comment by zonky2** [comment]
ist das Auftreten an bestimmte Bilder/Dateien gekoppelt, d.h. bei bestimmten Dateien tritt der Fehler auf bei anderen nicht?

**Comment by stefanmeschke** [comment]
Der Fehler tritt an unterschiedlichen Dateien (PDF, JPG, PNG etc.) auf.

**Comment by stefanmeschke** [comment]
@zonky2 
Das **attribute_select** verhindert leider das Update des DCG.

**Comment by zonky2** [comment]
...ich meinte nicht Datei-Arten sondern dezidierte Dateien ... oder kommt es vor, dass bei ein und der selben Datei der Fahler mal auftritt und mal nicht?

**Comment by zonky2** [comment]
> Das attribute_select verhindert leider das Update des DCG.

an das ```as 2.0.0``` in der JSON gedacht? - siehe Handbuch

**Comment by stefanmeschke** [comment]
Korrekt. Bei ein und derselben Datei kommt erst der Fehler, nach erneutem Auswählen und speichern kein Fehler. Dann evtl. nochmal speichern und dann kann es vorkommen, dass der Fehler wieder kommt.

**Comment by zonky2** [comment]
... bin da kein Fachmann, aber klingt für mich als ob die Zugriffe auf die Datei nicht immer möglich wären... ist der Server "home brew"?

**Comment by gruenerPetz** [comment]
> ist der Server "home brew"?
Server läuft auf Ubuntu.

Komisch ist auch, dass jede andere Art und Weise eine Datei hochzuladen und einzubinden (Core Inhaltselement etc.) keinerlei Probleme macht. Nur wenn man das über das MM machen möchte.

**Comment by zonky2** [comment]
einen (Groß-)Teil des Filehandlings übernimmt der DCG...
da man das anscheinend auf einem anderen Server nicht nachvollziehen kann, müsstet Ihr selbst raus finden, an welcher Stelle die Säge klemmt :-(

**Comment by stefanmeschke** [comment]
Ein weiteres Fehlverhalten konnte ich bei den letzten Dateien beobachten:

Ich wähle eine Datei aus dem Modal aus und gehe danach auf "Anwenden". Jetzt wird ein XHR-Request gemacht mit:

- URL: contao/main.php
- GET-Parameter:
-- do:metamodel_mm_downloads
-- after:mm_downloads::48
-- act:edit
-- id:mm_downloads::49
-- rt:5561e280059ea3eaebc2457a2970444f
-- ref:c1466c6e
- Form Data:
-- action:reloadFiletree
-- name:file
-- value:files/......pdf
-- REQUEST_TOKEN:5561e280059ea3eaebc2457a2970444f

Manchmal kommt hier auch ein leerer Response zurück. Folglich sehe ich die Ladeanimation und muss die Seite neu laden. In der Konsole von Google Chrome kommt dan POST gefolgt von der URL gefolgt von *net::ERR_EMPTY_RESPONSE*

**Comment by zonky2** [comment]
ist das Verhalten bei verschiedenen Browsern gleich?
sind irgendwelche lokalen Virenscanner oder Popupblocker am Start?

**Comment by stefanmeschke** [comment]
> ist das Verhalten bei verschiedenen Browsern gleich?
Ja. Tritt sowohl unter Chrome als auch unter Firefox auf.

> sind irgendwelche lokalen Virenscanner oder Popupblocker am Start?
Nein.

**Comment by zonky2** [comment]
... habe keine Idden mehr dazu :-(

**Comment by discordier** [comment]
Me non neither.

Without further information impossible to track this down.

Will close therefore, if you have additional information, feel free to reopen.
