### ISSUE TITLE
read only attribute doesn´t work

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_file#53]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    5.6      |                                  |
| Contao version:                     |    3.5.19      |                                  |
| MetaModels version:                 |   a14       |                                  |
| Installation via composer           | (yes) |                                  |
| Installed MetaModels packages       |          |                                  |

## Issue description

select readonly für input mask - you can choose a new file

**Comment by discordier** [comment]
`File::getFieldDefinition()` should pass eval read only. In addition, I suspect the file picker widget does not know what read only is about.

**Comment by zonky2** [comment]
Fixed in MM 2.2 with DCG 2.2
