### ISSUE TITLE
add meta data to raw data

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_file#54]
add meta data to raw data as new node - output as serialisized data or array

look at
https://github.com/MetaModels/attribute_file/blob/977ad4505bf1c2796d90e64e2b5e616e01f7e70f/src/MetaModels/Attribute/File/File.php#L100

change ToolboxFile:
https://github.com/MetaModels/core/blob/4e8303f6d7ce29f01bfd22867ab650444cf700e2/src/MetaModels/Helper/ToolboxFile.php#L757

**Comment by discordier** [comment]
I have no clue what you are talking about. Why should we do this?

**Comment by zonky2** [comment]
e.g. wie have a image file and we show the description, title, link or other meta data, we "ask" contao dateabase at every file  like

```
<?php foreach($arrItem['raw']['contact_logos']['bin'] as $strImageBin): ?>
<?php
	$objFile = \FilesModel::findByUuid($strImageBin);
	$arrFileMeta = unserialize($objFile->meta);
?>
...
```

may be we can output as option

**Comment by discordier** [comment]
Ah, now I get it.
Yeah, we can do this.

**Comment by zonky2** [comment]
may be - it the file a image we can add the original witdh and hight

**Comment by zonky2** [comment]
PR at https://github.com/MetaModels/core/pull/1116
