### ISSUE TITLE
<img>-Tag isn't generated at SVG-files

### ISSUE THREAD

**Issue by Sukrams** [MetaModels/attribute_file#58]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.1.8         |                                  |
| Contao version:                     | 3.5.29         |                                  |
| MetaModels version:                 |2.0.0          |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       | bundle/all         |                                  |

## Issue description

When I'm using a file-attribute e.g. for pictures or illustrations, there is no <img>-Tag generated in the sourcecode, when I'm using a SVG-File. So nothing is shown

## Steps to reproduce

1. Create a file-attribute maybe for svgs and configurate the output (HTML5)
2. Upload/choose a SVG
3. Check maybe Backend or Frontend
4. Nothing will shown.

## Describe the behaviour of the application

When I use a SVG-File in the file-attribute and generate the output via the standard (not edited) files, there is nothing shown. There is no <img>-Tag within the Metamodel. The part where the image should be is empty:

````
<ul class="file"> 
    <li class=" first last even"> 
                    
    </li> 
</ul>
````

## Describe the expected behaviour of the application

A file-attribute with a svg should generated correctly.

## Screenshots

<img width="907" alt="bildschirmfoto 2017-09-30 um 22 29 48" src="https://user-images.githubusercontent.com/15678176/31049247-88eb0798-a62f-11e7-9b42-8f915f93df6b.png">

<img width="263" alt="bildschirmfoto 2017-09-30 um 22 30 03" src="https://user-images.githubusercontent.com/15678176/31049245-8339454e-a62f-11e7-8863-b1f135a9c1ee.png">

**Comment by discordier** [comment]
Fixed in 1d8cd6a
