### ISSUE TITLE
"Order By" Sorting of files not working in FE Template

### ISSUE THREAD

**Issue by cmerz1** [MetaModels/attribute_file#62]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   7.1       |                                  |
| Contao version:                     |  3.5.30        |                                  |
| MetaModels version:                 |  2.0.0 alpha-16        |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |          |                                  |

The "order by" option in the render setting of a file or translatedfile attribute has the following effetct in the FE debug template:
raw: no effect -> files are always ordered by file name ascending
text: no effect -> files are always ordered by file name ascending
html5 -> incorrect order if there are more than 2 files

**Comment by zonky2** [comment]
kann ich bestätigen

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/pull/1217

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cmerz1 could you please have a final look at this and tell if your issue has been resolved?

**Comment by HaraldHubinger** [comment]
In our MM 2.1 installation (Contao 4.4.35, PHP 7.3) sorting by file attribute is broken with upgrade from MM 2.0 to MM 2.1. The same template renders  a correctly sorted list in MM 2.0 / Contao 3.5.36 and I could not find any other source of failure so for. Maybe this has to be reopened for MM 2.1?

**Comment by zonky2** [comment]
I have tested the sorting options for the FE output and found no errors.

**Comment by HaraldHubinger** [comment]
In addition to the Contao 3.5/MM2.0-installation, which broke regarding to file sorting I have now set up a fresh test-installation with a MM with a file-attribute.
I cannot achieve a Frontend output sorted by file, neither by setting it in the CE Metamodel-List nor by overrding it via "orderBy/file" (the name of the attribute). Sorting works perfectly indeed for all other attributes by just changing the value in the dropdown of the CE Metamodel List. Do you have an an idea, what could be wrong? The behaviour I'd expect (and had in the old installation) is an output sorted by the name of the file.

**Comment by zonky2** [comment]
> I cannot achieve a Frontend output sorted by file, neither by setting it in the CE Metamodel-List nor by overrding it via "orderBy/file" (the name of the attribute). 

Hi,
do you want to sort multiple files or sort a list of MM items by the file attribute?

maybe call me at skype :D

**Comment by zonky2** [comment]
@HaraldHubinger wants to filter several items according to the file attribute...

apparently this worked in MM 2.0 times... hmm??

**Comment by zonky2** [comment]
for such a requirement you could create your own filter type, which takes over the sorting
