### ISSUE TITLE
Todo before release 2.0.6

### ISSUE THREAD

**Issue by baumannsven** [MetaModels/attribute_file#72]
Before we release the new version, somethings must be do.

Backport some changes from mm core 2.1 => 2.0:
- [x] https://github.com/MetaModels/core/commit/65203d2544ebfd36436ffbd8e9db576a60ef9541

**Comment by discordier** [comment]
Was backported in https://github.com/MetaModels/core/commit/823e9f19910c805eeead4e65568a7baa397066a8
