### ISSUE TITLE
Table column queries are not cached in AttributeOrderTypeFactory

### ISSUE THREAD

**Issue by bezin** [MetaModels/attribute_file#76]
Hi all,

I have a collection of 100 Items with one file attribute. The following query was called 200 times, when requesting this collection:

```sql
SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'database' AND TABLE_NAME = 'mm_event'
```

Since this does not change within a request we should cache this response. 

PR follows

Cheerio

**Comment by zonky2** [comment]
fixed in https://github.com/MetaModels/attribute_file/pull/77
