### ISSUE TITLE
Change the checkbox Mehrfachauswahl in MM 2.2@dev create a SQL error

### ISSUE THREAD

**Issue by stu2019** [MetaModels/attribute_file#96]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |7.4.16          |                                  |
| Contao version:                     |4.9.13          |                                  |
| MetaModels version:                 |2.2@dev          |                                  |
| Installation via composer           | (yes) |                                  |
| Installed MetaModels packages       | all         |                                  |

## Issue description
(Describe the problem you are having)
Change the checkbox Mehrfachauswahl for an attribute file in an existing Metamodels create the error message
An exception occurred while executing 'ALTER TABLE `mm_mitarbeiterliste` ADD `Bid_test__sort` blob NULL': SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Bid_test__sort'

## Steps to reproduce
I did an update from MM 2.1 to MM 2.2.
This issue seem to exist ONLY in MetaModes coming from/created in MM 2.1
I do have an existing metamodel A.
There I create a new attribute file (Datei). Name it Bildtest1. 
I check the setting Mehrfachauswahl.
Save and close.
Reopen the attribute. Uncheck Mehrfachauswahl.
Save and close -> all fine.
Reopen the attribute once more. Check Mehrfachauswahl again..
Save and close -> I get the following error-message:
An exception occurred while executing 'ALTER TABLE `mm_mitarbeiterliste` ADD `Bid_test__sort` blob NULL': SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Bid_test__sort'

I can reproduce this behavior in every existing MetaModel.

BUT: If I create an new MetaModel and do the same steps -> No error message will be displayed. Everything works fine.

## Screenshots

https://user-images.githubusercontent.com/49641522/113897234-f84e4880-97ca-11eb-98eb-7be831d47bde.mov

[prod-2021-04-07.log](https://github.com/MetaModels/attribute_file/files/6272871/prod-2021-04-07.log)
[installierte module.txt](https://github.com/MetaModels/attribute_file/files/6272882/installierte.module.txt)

**Comment by zonky2** [comment]
@baumannsven sounds like a check for existing column is not working properly....

**Comment by zonky2** [comment]
@stu2019 pls check with current MM 2.2 - I cannot understand the error
