### ISSUE TITLE
FEE - File / Image upload with unchecked attribute setting Mehrfachauswahl and Single file upload does not work

### ISSUE THREAD

**Issue by stu2019** [MetaModels/attribute_file#97]
I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue
Maybe it is related to #92 

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.4.16      |                                  |
| Contao version:                     |      4.9.13	   |                                  |
| MetaModels version:                 |     2.2@dev	     |                                  |
| Installation via composer           | (yes) |                                  |
| Installed MetaModels packages       |      all    |                                  |

## Issue description
With FEE I try to upload a File / Image. This will show an error message and the file is not uploaded. 

## Steps to reproduce
Settings are:
In attribute file the attribute setting Mehrfachauswahl is unchecked (see screenshot).
In Eingabemaske the  Single file upload with show thumbnail [only for frontend editing] is chosen.
Open the configured FEE Detail Page in the Browser.
Drag the new image to the drop zone.
Save.
## Describe the behaviour of the application
The error pops up.
Property bild (file) did not accept the value (The values differ. Encountered type string expected array (Found '����넄' . "\0" . 'J', expected array ( 0 => '����넄' . "\0" . 'J', ))).

Check in the backend: the File is not uploaded.

## Describe the expected behaviour of the application
The file should be changed to the new version.

## Screenshots
[installierte module.txt](https://github.com/MetaModels/attribute_file/files/6273218/installierte.module.txt)
<img width="1314" alt="Bildschirmfoto 2021-04-07 um 18 48 15" src="https://user-images.githubusercontent.com/49641522/113904112-fd62c600-97d1-11eb-9e2e-8bcdd44dba5f.png">
<img width="1373" alt="Bildschirmfoto 2021-04-07 um 18 45 12" src="https://user-images.githubusercontent.com/49641522/113904149-0a7fb500-97d2-11eb-9f2b-0850b8242671.png">

https://user-images.githubusercontent.com/49641522/113904916-dbb60e80-97d2-11eb-8c37-41ce4e954a3e.mov

**Comment by zonky2** [comment]
Both single uplod modes are set to deprecated and should no longer be used.
